#!/bin/bash

VERSION=$(cat VERSION)
REPO="MinecraftRecipeMaker"

# Run Compile
. ./script/compile

if [ -d pkg ];then
  rm -rf ./pkg/dist
fi

# Package all binary as .zip
mkdir -p ./pkg/dist/${VERSION}
for PLATFORM in $(find ./pkg -mindepth 1 -maxdepth 1 -type d); do
  PLATFORM_NAME=$(basename ${PLATFORM})
  ARCHIVE_NAME=${REPO}_${VERSION}_${PLATFORM_NAME}
  if [ $PLATFORM_NAME = "dist" ]; then
    continue
  fi

  pushd ${PLATFORM}
  cp -r ${DIR}/_template config
  zip -r ${DIR}/pkg/dist/${VERSION}/${ARCHIVE_NAME}.zip ./*
  rm -rf config
  popd
done

# Generate shasum
pushd ./pkg/dist/${VERSION}
shasum * > ./${VERSION}_SHASUMS
popd
